[Node.P2P]
StaticNodes = [
  "enode://49d038000237a5a46566fd026dc543ba1320051a32e80079d9eaea2e9617912769bfc76af6020b50fd1be81574835c29a6ad1cf9734985ff449f2b74fe0d09ee@172.25.0.102:30303",
  "enode://8e40bb7d0aec29170825ea98d4151b402a65b2179abc83268fde39f3d1a219c2370ef08297163eda40dd5d74cad0d4104a226670e6e36e75bc2ce34745e3c8a3@172.25.0.103:30303"
]
MaxPeers = 50
