[Node.P2P]
StaticNodes = [
  "enode://bacf86b2c979e41b0cd5c76cbd0f91c2f6b9825e367574d40f92ff220c8b3cafd371974724bf7007c2ad0dcc544a0d04e1052cd788b485869dc16764bf250123@172.25.0.101:30303",
  "enode://8e40bb7d0aec29170825ea98d4151b402a65b2179abc83268fde39f3d1a219c2370ef08297163eda40dd5d74cad0d4104a226670e6e36e75bc2ce34745e3c8a3@172.25.0.103:30303"
]
MaxPeers = 50
