[Node.P2P]
StaticNodes = [
  "enode://bacf86b2c979e41b0cd5c76cbd0f91c2f6b9825e367574d40f92ff220c8b3cafd371974724bf7007c2ad0dcc544a0d04e1052cd788b485869dc16764bf250123@172.25.0.101:30303",
  "enode://49d038000237a5a46566fd026dc543ba1320051a32e80079d9eaea2e9617912769bfc76af6020b50fd1be81574835c29a6ad1cf9734985ff449f2b74fe0d09ee@172.25.0.102:30303"
]
MaxPeers = 50
